#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KORDSA_UTP
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KORDSA_STP")]
	public partial class VeriTabaniBaglantiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertHurda(Hurda instance);
    partial void UpdateHurda(Hurda instance);
    partial void DeleteHurda(Hurda instance);
    partial void InsertStok(Stok instance);
    partial void UpdateStok(Stok instance);
    partial void DeleteStok(Stok instance);
    #endregion
		
		public VeriTabaniBaglantiDataContext() : 
				base(global::KORDSA_UTP.Properties.Settings.Default.KORDSA_STPConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public VeriTabaniBaglantiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VeriTabaniBaglantiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VeriTabaniBaglantiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public VeriTabaniBaglantiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Hurda> Hurdas
		{
			get
			{
				return this.GetTable<Hurda>();
			}
		}
		
		public System.Data.Linq.Table<Stok> Stoks
		{
			get
			{
				return this.GetTable<Stok>();
			}
		}
		
		public System.Data.Linq.Table<Login> Logins
		{
			get
			{
				return this.GetTable<Login>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hurda")]
	public partial class Hurda : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HurdaID;
		
		private string _HurdaIsim;
		
		private string _HurdaAdet;
		
		private string _HurdaRafNo;
		
		private string _HurdaModel;
		
		private string _HurdaSeriNo;
		
		private System.DateTime _HurdaStokGirisTarih;
		
		private string _ElemanIsim;
		
		private string _Aciklama;
		
		private System.DateTime _HurdaOlusTarih;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHurdaIDChanging(int value);
    partial void OnHurdaIDChanged();
    partial void OnHurdaIsimChanging(string value);
    partial void OnHurdaIsimChanged();
    partial void OnHurdaAdetChanging(string value);
    partial void OnHurdaAdetChanged();
    partial void OnHurdaRafNoChanging(string value);
    partial void OnHurdaRafNoChanged();
    partial void OnHurdaModelChanging(string value);
    partial void OnHurdaModelChanged();
    partial void OnHurdaSeriNoChanging(string value);
    partial void OnHurdaSeriNoChanged();
    partial void OnHurdaStokGirisTarihChanging(System.DateTime value);
    partial void OnHurdaStokGirisTarihChanged();
    partial void OnElemanIsimChanging(string value);
    partial void OnElemanIsimChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    partial void OnHurdaOlusTarihChanging(System.DateTime value);
    partial void OnHurdaOlusTarihChanged();
    #endregion
		
		public Hurda()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HurdaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int HurdaID
		{
			get
			{
				return this._HurdaID;
			}
			set
			{
				if ((this._HurdaID != value))
				{
					this.OnHurdaIDChanging(value);
					this.SendPropertyChanging();
					this._HurdaID = value;
					this.SendPropertyChanged("HurdaID");
					this.OnHurdaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HurdaIsim", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HurdaIsim
		{
			get
			{
				return this._HurdaIsim;
			}
			set
			{
				if ((this._HurdaIsim != value))
				{
					this.OnHurdaIsimChanging(value);
					this.SendPropertyChanging();
					this._HurdaIsim = value;
					this.SendPropertyChanged("HurdaIsim");
					this.OnHurdaIsimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HurdaAdet", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HurdaAdet
		{
			get
			{
				return this._HurdaAdet;
			}
			set
			{
				if ((this._HurdaAdet != value))
				{
					this.OnHurdaAdetChanging(value);
					this.SendPropertyChanging();
					this._HurdaAdet = value;
					this.SendPropertyChanged("HurdaAdet");
					this.OnHurdaAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HurdaRafNo", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HurdaRafNo
		{
			get
			{
				return this._HurdaRafNo;
			}
			set
			{
				if ((this._HurdaRafNo != value))
				{
					this.OnHurdaRafNoChanging(value);
					this.SendPropertyChanging();
					this._HurdaRafNo = value;
					this.SendPropertyChanged("HurdaRafNo");
					this.OnHurdaRafNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HurdaModel", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HurdaModel
		{
			get
			{
				return this._HurdaModel;
			}
			set
			{
				if ((this._HurdaModel != value))
				{
					this.OnHurdaModelChanging(value);
					this.SendPropertyChanging();
					this._HurdaModel = value;
					this.SendPropertyChanged("HurdaModel");
					this.OnHurdaModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HurdaSeriNo", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HurdaSeriNo
		{
			get
			{
				return this._HurdaSeriNo;
			}
			set
			{
				if ((this._HurdaSeriNo != value))
				{
					this.OnHurdaSeriNoChanging(value);
					this.SendPropertyChanging();
					this._HurdaSeriNo = value;
					this.SendPropertyChanged("HurdaSeriNo");
					this.OnHurdaSeriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HurdaStokGirisTarih", DbType="DateTime NOT NULL")]
		public System.DateTime HurdaStokGirisTarih
		{
			get
			{
				return this._HurdaStokGirisTarih;
			}
			set
			{
				if ((this._HurdaStokGirisTarih != value))
				{
					this.OnHurdaStokGirisTarihChanging(value);
					this.SendPropertyChanging();
					this._HurdaStokGirisTarih = value;
					this.SendPropertyChanged("HurdaStokGirisTarih");
					this.OnHurdaStokGirisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElemanIsim", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ElemanIsim
		{
			get
			{
				return this._ElemanIsim;
			}
			set
			{
				if ((this._ElemanIsim != value))
				{
					this.OnElemanIsimChanging(value);
					this.SendPropertyChanging();
					this._ElemanIsim = value;
					this.SendPropertyChanged("ElemanIsim");
					this.OnElemanIsimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(MAX)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HurdaOlusTarih", DbType="DateTime NOT NULL")]
		public System.DateTime HurdaOlusTarih
		{
			get
			{
				return this._HurdaOlusTarih;
			}
			set
			{
				if ((this._HurdaOlusTarih != value))
				{
					this.OnHurdaOlusTarihChanging(value);
					this.SendPropertyChanging();
					this._HurdaOlusTarih = value;
					this.SendPropertyChanged("HurdaOlusTarih");
					this.OnHurdaOlusTarihChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Stok")]
	public partial class Stok : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StokID;
		
		private string _StokIsim;
		
		private string _StokAdet;
		
		private string _StokRafNo;
		
		private string _StokModel;
		
		private string _StokSeriNo;
		
		private System.DateTime _StokTarih;
		
		private string _ElemanIsim;
		
		private string _Aciklama;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStokIDChanging(int value);
    partial void OnStokIDChanged();
    partial void OnStokIsimChanging(string value);
    partial void OnStokIsimChanged();
    partial void OnStokAdetChanging(string value);
    partial void OnStokAdetChanged();
    partial void OnStokRafNoChanging(string value);
    partial void OnStokRafNoChanged();
    partial void OnStokModelChanging(string value);
    partial void OnStokModelChanged();
    partial void OnStokSeriNoChanging(string value);
    partial void OnStokSeriNoChanged();
    partial void OnStokTarihChanging(System.DateTime value);
    partial void OnStokTarihChanged();
    partial void OnElemanIsimChanging(string value);
    partial void OnElemanIsimChanged();
    partial void OnAciklamaChanging(string value);
    partial void OnAciklamaChanged();
    #endregion
		
		public Stok()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int StokID
		{
			get
			{
				return this._StokID;
			}
			set
			{
				if ((this._StokID != value))
				{
					this.OnStokIDChanging(value);
					this.SendPropertyChanging();
					this._StokID = value;
					this.SendPropertyChanged("StokID");
					this.OnStokIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokIsim", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StokIsim
		{
			get
			{
				return this._StokIsim;
			}
			set
			{
				if ((this._StokIsim != value))
				{
					this.OnStokIsimChanging(value);
					this.SendPropertyChanging();
					this._StokIsim = value;
					this.SendPropertyChanged("StokIsim");
					this.OnStokIsimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokAdet", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StokAdet
		{
			get
			{
				return this._StokAdet;
			}
			set
			{
				if ((this._StokAdet != value))
				{
					this.OnStokAdetChanging(value);
					this.SendPropertyChanging();
					this._StokAdet = value;
					this.SendPropertyChanged("StokAdet");
					this.OnStokAdetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokRafNo", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StokRafNo
		{
			get
			{
				return this._StokRafNo;
			}
			set
			{
				if ((this._StokRafNo != value))
				{
					this.OnStokRafNoChanging(value);
					this.SendPropertyChanging();
					this._StokRafNo = value;
					this.SendPropertyChanged("StokRafNo");
					this.OnStokRafNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokModel", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StokModel
		{
			get
			{
				return this._StokModel;
			}
			set
			{
				if ((this._StokModel != value))
				{
					this.OnStokModelChanging(value);
					this.SendPropertyChanging();
					this._StokModel = value;
					this.SendPropertyChanged("StokModel");
					this.OnStokModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokSeriNo", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StokSeriNo
		{
			get
			{
				return this._StokSeriNo;
			}
			set
			{
				if ((this._StokSeriNo != value))
				{
					this.OnStokSeriNoChanging(value);
					this.SendPropertyChanging();
					this._StokSeriNo = value;
					this.SendPropertyChanged("StokSeriNo");
					this.OnStokSeriNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StokTarih", DbType="DateTime NOT NULL")]
		public System.DateTime StokTarih
		{
			get
			{
				return this._StokTarih;
			}
			set
			{
				if ((this._StokTarih != value))
				{
					this.OnStokTarihChanging(value);
					this.SendPropertyChanging();
					this._StokTarih = value;
					this.SendPropertyChanged("StokTarih");
					this.OnStokTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ElemanIsim", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ElemanIsim
		{
			get
			{
				return this._ElemanIsim;
			}
			set
			{
				if ((this._ElemanIsim != value))
				{
					this.OnElemanIsimChanging(value);
					this.SendPropertyChanging();
					this._ElemanIsim = value;
					this.SendPropertyChanged("ElemanIsim");
					this.OnElemanIsimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Aciklama", DbType="NVarChar(MAX)")]
		public string Aciklama
		{
			get
			{
				return this._Aciklama;
			}
			set
			{
				if ((this._Aciklama != value))
				{
					this.OnAciklamaChanging(value);
					this.SendPropertyChanging();
					this._Aciklama = value;
					this.SendPropertyChanged("Aciklama");
					this.OnAciklamaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Login")]
	public partial class Login
	{
		
		private System.Nullable<System.Guid> _LoginID;
		
		private string _LoginKullaniciAdi;
		
		private string _LoginSifre;
		
		public Login()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> LoginID
		{
			get
			{
				return this._LoginID;
			}
			set
			{
				if ((this._LoginID != value))
				{
					this._LoginID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginKullaniciAdi", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string LoginKullaniciAdi
		{
			get
			{
				return this._LoginKullaniciAdi;
			}
			set
			{
				if ((this._LoginKullaniciAdi != value))
				{
					this._LoginKullaniciAdi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginSifre", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string LoginSifre
		{
			get
			{
				return this._LoginSifre;
			}
			set
			{
				if ((this._LoginSifre != value))
				{
					this._LoginSifre = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
