<?xml version="1.0" encoding="utf-8"?><Database Name="KORDSA_STP" Class="VeriTabaniBaglantiDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-2SDAQ0JP\TIBETSQL;Initial Catalog=KORDSA_STP;User ID=sa" SettingsObjectName="KORDSA_UTP.Properties.Settings" SettingsPropertyName="KORDSA_STPConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Hurda" Member="Hurdas">
    <Type Name="Hurda">
      <Column Name="HurdaID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HurdaIsim" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="HurdaAdet" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="HurdaRafNo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="HurdaModel" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="HurdaSeriNo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="HurdaStokGirisTarih" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ElemanIsim" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Aciklama" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HurdaOlusTarih" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Stok" Member="Stoks">
    <Type Name="Stok">
      <Column Name="StokID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StokIsim" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StokAdet" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StokRafNo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StokModel" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StokSeriNo" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="StokTarih" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ElemanIsim" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Aciklama" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Login" Member="Logins">
    <Type Name="Login">
      <Column Name="LoginID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="LoginKullaniciAdi" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="LoginSifre" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>